name: "Tests"

on: [ pull_request ]
jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2

      - name: Set PHP version env
        run: export PHP_VERSION=${{ matrix.php-versions }}

      - name: Build
        run: |
          docker compose build
          docker compose up -d
          sleep 10

      - name: Run Tests
        run: docker compose exec tests vendor/bin/phpunit --configuration phpunit.xml tests